name: Splunk App Dowmloader workflow 3

on: push

jobs:
  Splunk_app_downloader:
    name: Splunk App Job 3
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          lfs: true
          fetch-depth: 0
          ref: main
      - name: Checkout LFS objects
        run: git lfs checkout
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          ls -l
          du -sh SplunkBase/
          cd .git
          ls -l
          pwd
          git config --global http.version HTTP/1.1
          git config --global http.postBuffer 157286400
        shell: bash
      - name: Install the LFS
        run: |
          mkdir lsf
          cd lfs
          git --version
          curl -L -J -O https://github.com/git-lfs/git-lfs/releases/download/v2.9.0/git-lfs-linux-amd64-v2.9.0.tar.gz
          tar -xf git-lfs-linux-amd64-v2.9.0.tar.gz
          chmod 755 install.sh
          sudo ./install.sh
          git lfs install
          git lfs track "*.tgz"
          git add .gitattributes
          cat .gitattributes          
      - name: Run a shell script file
        run: sh ./workflow/scripts/app_downloader_3.sh
        shell: bash
        env:
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
