name: Splunk App Dowmloader workflow 1

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "0 * * * *"

jobs:
  Splunk_app_downloader:
    name: Splunk App Job 1
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
          ref: main
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          ls -l
          du -sh SplunkBase/
        shell: bash
      - name: Run a shell script file
        run: sh ./workflow/scripts/app_downloader_1.sh
        shell: bash
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
