name: Splunk App Dowmloader workflow

on: push

jobs:
  Splunk_app_downloader:
    name: Splunk App Job
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
          ref: main
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          ls -l
          cat /home/runner/work/Splunk_Apps/Splunk_Apps/splunk_token.txt | awk '{print $3}'
          echo "2nd command"
          ls | grep -c SplunkBase
        shell: bash
      - name: Run a shell script file
        run: sh ./app_downloader.sh
        shell: bash
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
