name: Splunk App Dowmloader workflow

on: push

jobs:
  Splunk_app_downloader:
    name: Splunk App Job
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          ls -l
          echo "1st command"
          pwd
          cd SplunkBase
          echo "last command"
          ls -l
