name: Splunk App Dowmloader workflow

on: push

jobs:
  Splunk_app_downloader:
    name: Splunk App Job
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
