name: Splunk App Dowmloader workflow 4

on: push

jobs:
  Splunk_app_downloader:
    name: Splunk App Job 4
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
          ref: main
      - run: echo "This repo is ${{ github.repository }} .."
      - name: Run a inline script
        run: |
          ls -l
          du -sh SplunkBase/
          mkdir .git
          echo "Test filr in Config" > .git/config
          cat .git/config
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
